import type { ZReport } from "@/lib/fm-types";

export const zReportFieldLabels: Record<keyof ZReport, string> = {
  DateTime: "Дата/час",
  ZNumber: "Номер Z-звіту",
  FMNumChanges: "Зміни ФМ",
  TaxNumChanges: "Зміни податкового",
  VatChanges: "Зміни ПДВ",
  RamResetsCount: "Скидання RAM",
  FiscalCount: "Фіскальний лічильник",
  StornoCount: "Лічильник повернень",
  LastDocument: "Останній документ",
  LastFiscal: "Останній фіскальний",
  LastStorno: "Останній сторно",
  ObigVatA: "Обіг A",
  ObigVatB: "Обіг Б",
  ObigVatC: "Обіг В",
  ObigVatD: "Обіг Г",
  ObigVatE: "Обіг Д",
  ObigVatF: "Обіг Е",
  ObigVatG: "Обіг Ж",
  ObigVatH: "Обіг З",
  ObigVatAStorno: "Обіг A повернення",
  ObigVatBStorno: "Обіг Б повернення",
  ObigVatCStorno: "Обіг В повернення",
  ObigVatDStorno: "Обіг Г повернення",
  ObigVatEStorno: "Обіг Д повернення",
  ObigVatFStorno: "Обіг Е повернення",
  ObigVatGStorno: "Обіг Ж повернення",
  ObigVatHStorno: "Обіг З повернення",
  SumaVatA: "ПДВ A",
  SumaVatB: "ПДВ Б",
  SumaVatC: "ПДВ В",
  SumaVatD: "ПДВ Г",
  SumaVatE: "ПДВ Д",
  SumaVatF: "ПДВ Е",
  SumaVatG: "ПДВ Ж",
  SumaVatH: "ПДВ З",
  SumaVatAStorno: "ПДВ A повернення",
  SumaVatBStorno: "ПДВ Б повернення",
  SumaVatCStorno: "ПДВ В повернення",
  SumaVatDStorno: "ПДВ Г повернення",
  SumaVatEStorno: "ПДВ Д повернення",
  SumaVatFStorno: "ПДВ Е повернення",
  SumaVatGStorno: "ПДВ Ж повернення",
  SumaVatHStorno: "ПДВ З повернення",
  ZbirVatA: "Збір A",
  ZbirVatB: "Збір Б",
  ZbirVatC: "Збір В",
  ZbirVatD: "Збір Г",
  ZbirVatE: "Збір Д",
  ZbirVatF: "Збір Е",
  ZbirVatG: "Збір Ж",
  ZbirVatH: "Збір З",
  ZbirVatAStorno: "Збір A повернення",
  ZbirVatBStorno: "Збір Б повернення",
  ZbirVatCStorno: "Збір В повернення",
  ZbirVatDStorno: "Збір Г повернення",
  ZbirVatEStorno: "Збір Д повернення",
  ZbirVatFStorno: "Збір Е повернення",
  ZbirVatGStorno: "Збір Ж повернення",
  ZbirVatHStorno: "Збір З повернення",
  CheckSum: "Контрольна сума",
};
